import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { formatDate, calculatePercentage } from './helpers';

// Export attendance as PDF
export const exportToPDF = (courses, userInfo) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.text('Attendance Report', 14, 20);
  
  doc.setFontSize(10);
  doc.text(`Generated on: ${formatDate(new Date())}`, 14, 28);
  doc.text(`Student: ${userInfo.name || 'N/A'}`, 14, 34);
  doc.text(`Roll No: ${userInfo.roll_number || 'N/A'}`, 14, 40);
  
  // Table data
  const tableData = courses.map(course => [
    course.course_code,
    course.course_name,
    course.classes_attended,
    course.total_classes,
    `${calculatePercentage(course.classes_attended, course.total_classes)}%`,
    course.target_percentage + '%',
  ]);
  
  doc.autoTable({
    startY: 50,
    head: [['Code', 'Course Name', 'Attended', 'Total', 'Current %', 'Target %']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [74, 144, 226] },
  });
  
  // Summary
  const totalAttended = courses.reduce((sum, c) => sum + c.classes_attended, 0);
  const totalClasses = courses.reduce((sum, c) => sum + c.total_classes, 0);
  const overallPercentage = calculatePercentage(totalAttended, totalClasses);
  
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(12);
  doc.text(`Overall Attendance: ${overallPercentage}%`, 14, finalY);
  doc.text(`Total Classes: ${totalClasses}`, 14, finalY + 8);
  doc.text(`Classes Attended: ${totalAttended}`, 14, finalY + 16);
  
  // Footer
  doc.setFontSize(8);
  doc.text('Generated by Student Attendance Manager', 14, doc.internal.pageSize.height - 10);
  doc.text('This is not an official document', 14, doc.internal.pageSize.height - 6);
  
  doc.save(`attendance-report-${new Date().toISOString().split('T')[0]}.pdf`);
};

// Export attendance as Excel
export const exportToExcel = (courses, userInfo) => {
  const workbook = XLSX.utils.book_new();
  
  // Summary sheet
  const summaryData = [
    ['Student Attendance Report'],
    [''],
    ['Student Name:', userInfo.name || 'N/A'],
    ['Roll Number:', userInfo.roll_number || 'N/A'],
    ['Generated On:', formatDate(new Date())],
    [''],
    ['Course Code', 'Course Name', 'Classes Attended', 'Total Classes', 'Current %', 'Target %'],
  ];
  
  courses.forEach(course => {
    summaryData.push([
      course.course_code,
      course.course_name,
      course.classes_attended,
      course.total_classes,
      calculatePercentage(course.classes_attended, course.total_classes) + '%',
      course.target_percentage + '%',
    ]);
  });
  
  // Overall summary
  const totalAttended = courses.reduce((sum, c) => sum + c.classes_attended, 0);
  const totalClasses = courses.reduce((sum, c) => sum + c.total_classes, 0);
  
  summaryData.push(
    [''],
    ['Overall Attendance:', calculatePercentage(totalAttended, totalClasses) + '%'],
    ['Total Classes:', totalClasses],
    ['Classes Attended:', totalAttended]
  );
  
  const worksheet = XLSX.utils.aoa_to_sheet(summaryData);
  
  // Set column widths
  worksheet['!cols'] = [
    { wch: 15 },
    { wch: 30 },
    { wch: 15 },
    { wch: 15 },
    { wch: 12 },
    { wch: 12 },
  ];
  
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Attendance Report');
  
  XLSX.writeFile(workbook, `attendance-report-${new Date().toISOString().split('T')[0]}.xlsx`);
};

// Generate shareable text
export const generateShareText = (calculatorData) => {
  const { totalClasses, classesAttended, currentPercentage, classesNeeded, classesCanMiss, targetPercentage } = calculatorData;
  
  let text = `📊 My Attendance Status\n\n`;
  text += `Classes Attended: ${classesAttended}/${totalClasses}\n`;
  text += `Current Percentage: ${currentPercentage}%\n`;
  text += `Target: ${targetPercentage}%\n\n`;
  
  if (currentPercentage >= targetPercentage) {
    text += `✅ Status: Safe\n`;
    text += `Can miss: ${classesCanMiss} more classes\n`;
  } else {
    text += `⚠️ Need to attend: ${classesNeeded} more classes\n`;
  }
  
  text += `\n📱 Calculated using Student Attendance Manager`;
  
  return text;
};

// Copy to clipboard
export const copyToClipboard = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy:', error);
    return false;
  }
};
